tmux kill-session -t client-0
tmux kill-session -t client-1
tmux kill-session -t client-2
tmux kill-session -t executor-1
tmux kill-session -t executor-2
tmux kill-session -t primary-0
tmux kill-session -t primary-1
tmux kill-session -t primary-2
tmux kill-session -t worker-0-0
tmux kill-session -t worker-1-0
tmux kill-session -t worker-2-0
