[package]
name = "store"
version = "0.1.0"
authors = ["Alberto Sonnino <alberto@sonnino.com>"]
edition = "2018"
publish = false

[dependencies]
tokio = { version = "1.12.0", features = ["sync", "rt", "macros"] }
rocksdb = "0.22.0"
serde = "1.0.130"
bincode = "1.3.3"
