package common

const (
	NONE_TYPE                        = "none"
	VALIDATOR_CONNECTION_TYPE        = "validator"
	NODE_CONNECTION_TYPE             = "node"
	CHILD_NODE_CONNECTION_TYPE       = "child_node"
	EXECUTE_MINER_CONNECTION_TYPE    = "execute_miner"
	VERIFY_MINER_CONNECTION_TYPE     = "verify_miner"
	CLIENT_CONNECTION_TYPE           = "client"
	STORAGE_CONNECTION_TYPE          = "storage"
	EXPLORER_CONNECTION_TYPE         = "explorer"
	TEMP_CONNECTION_TYPE             = "temp"
	MASTER_CONNECTION_TYPE           = "master"
	MASTER_READ_ONLY_CONNECTION_TYPE = "master_read_only"

	EXEC_CONNECTION_TYPE = "exec"
	//
	STATE_CHANNEL_VALIDATOR_CONNECTION_TYPE = "state_channel_validator"
	BACKUP_CONNECTION_TYPE                  = "backup"
)

const (
	NONE_IDX                     = 0
	VALIDATOR_CONNECTION_IDX     = 1
	NODE_CONNECTION_IDX          = 2
	CHILD_NODE_CONNECTION_IDX    = 3
	EXECUTE_MINER_CONNECTION_IDX = 4
	VERIFY_MINER_CONNECTION_IDX  = 5
	CLIENT_CONNECTION_IDX        = 6
	STORAGE_CONNECTION_IDX       = 7
	EXPLORER_CONNECTION_IDX      = 8

	STATE_CHANNEL_VALIDATOR_CONNECTION_IDX = 9
	BACKUP_CONNECTION_IDX                  = 10
	MASTER_READ_ONLY_IDX                   = 11
)

func MapConnectionTypeToIndex(cSType string) int {
	switch cSType {
	case VALIDATOR_CONNECTION_TYPE:
		return VALIDATOR_CONNECTION_IDX
	case NODE_CONNECTION_TYPE:
		return NODE_CONNECTION_IDX
	case CHILD_NODE_CONNECTION_TYPE:
		return CHILD_NODE_CONNECTION_IDX
	case EXECUTE_MINER_CONNECTION_TYPE:
		return EXECUTE_MINER_CONNECTION_IDX
	case VERIFY_MINER_CONNECTION_TYPE:
		return VERIFY_MINER_CONNECTION_IDX
	case CLIENT_CONNECTION_TYPE:
		return CLIENT_CONNECTION_IDX
	case STORAGE_CONNECTION_TYPE:
		return STORAGE_CONNECTION_IDX
	case EXPLORER_CONNECTION_TYPE:
		return EXPLORER_CONNECTION_IDX
	case STATE_CHANNEL_VALIDATOR_CONNECTION_TYPE:
		return STATE_CHANNEL_VALIDATOR_CONNECTION_IDX
	case BACKUP_CONNECTION_TYPE:
		return BACKUP_CONNECTION_IDX
	case MASTER_READ_ONLY_CONNECTION_TYPE:
		return MASTER_READ_ONLY_IDX
	default:
		return NONE_IDX
	}
}

func MapIndexToConnectionType(index int) string {
	switch index {
	case VALIDATOR_CONNECTION_IDX:
		return VALIDATOR_CONNECTION_TYPE
	case NODE_CONNECTION_IDX:
		return NODE_CONNECTION_TYPE
	case CHILD_NODE_CONNECTION_IDX:
		return CHILD_NODE_CONNECTION_TYPE
	case EXECUTE_MINER_CONNECTION_IDX:
		return EXECUTE_MINER_CONNECTION_TYPE
	case VERIFY_MINER_CONNECTION_IDX:
		return VERIFY_MINER_CONNECTION_TYPE
	case CLIENT_CONNECTION_IDX:
		return CLIENT_CONNECTION_TYPE
	case STORAGE_CONNECTION_IDX:
		return STORAGE_CONNECTION_TYPE
	case EXPLORER_CONNECTION_IDX:
		return EXPLORER_CONNECTION_TYPE
	case STATE_CHANNEL_VALIDATOR_CONNECTION_IDX:
		return STATE_CHANNEL_VALIDATOR_CONNECTION_TYPE
	case BACKUP_CONNECTION_IDX:
		return BACKUP_CONNECTION_TYPE
	default:
		return NONE_TYPE
	}
}
